Update postBuild

diff --git a/.binder/postBuild b/.binder/postBuild
--- a/.binder/postBuild
+++ b/.binder/postBuild
@@ -29,10 +29,20 @@ make install
 # Cleanup AWS SDK build
 cd /tmp && rm -rf aws-sdk-cpp
 
+# Set up environment for netCDF to find AWS SDK
+export PKG_CONFIG_PATH=${CONDA_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}
+export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}
+export CMAKE_PREFIX_PATH=${CONDA_PREFIX}:${CMAKE_PREFIX_PATH}
+
 # Now build netcdf-c with Zarr support
 git clone --depth 1 --branch zarr-csl-fully https://github.com/mannreis/netcdf-c.git /tmp/netcdf-c
 cd /tmp/netcdf-c
 mkdir build && cd build
+
+# Check if AWS SDK is findable
+echo "Checking for AWS SDK libraries:"
+ls -la ${CONDA_PREFIX}/lib/libaws* || echo "AWS libraries not found in expected location"
+ls -la ${CONDA_PREFIX}/lib/cmake/AWSSDK/ || echo "AWS CMake configs not found"
 
 cmake .. \
   -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
@@ -44,7 +54,10 @@ cmake .. \
   -DNETCDF_ENABLE_S3=ON \
   -DNETCDF_ENABLE_NCZARR_S3=ON \
   -DNETCDF_ENABLE_NCZARR_ZIP=ON \
-  -DPLUGIN_INSTALL_DIR=${CONDA_PREFIX}/lib/netcdf/plugins
+  -DPLUGIN_INSTALL_DIR=${CONDA_PREFIX}/lib/netcdf/plugins \
+  -DAWSSDK_ROOT_DIR=${CONDA_PREFIX} \
+  -DAWSSDK_INCLUDE_DIR=${CONDA_PREFIX}/include \
+  -DAWSSDK_LIB_DIR=${CONDA_PREFIX}/lib
 
 make -j2
 make install
