Update postBuild

diff --git a/.binder/postBuild b/.binder/postBuild
--- a/.binder/postBuild
+++ b/.binder/postBuild
@@ -1,46 +1,64 @@
 #!/bin/bash
 set -ex
 
-# Clone the specific zarr-enabled branch
-git clone --depth 1 --branch zarr-csl-fully https://github.com/mannreis/netcdf-c.git /tmp/netcdf-c
+# Set conda prefix if not set
+export CONDA_PREFIX=${CONDA_PREFIX:-${NB_PYTHON_PREFIX}}
 
-cd /tmp/netcdf-c
+# Install AWS SDK for C++ from source (lightweight S3-only build)
+cd /tmp
+git clone --recurse-submodules --depth 1 --branch 1.11.200 https://github.com/aws/aws-sdk-cpp.git
+cd aws-sdk-cpp
 mkdir build && cd build
 
-# Configure with Zarr and S3 support enabled
 cmake .. \
   -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
   -DCMAKE_BUILD_TYPE=Release \
-  -DENABLE_TESTS=OFF \
-  -DENABLE_DAP=ON \
-  -DENABLE_NCZARR=ON \
-  -DENABLE_S3=ON \
-  -DENABLE_NCZARR_S3=ON \
-  -DENABLE_NCZARR_ZIP=ON \
+  -DBUILD_ONLY="s3" \
+  -DENABLE_TESTING=OFF \
+  -DBUILD_SHARED_LIBS=ON \
+  -DCMAKE_INSTALL_LIBDIR=lib
+
+make -j2
+make install
+
+# Cleanup AWS SDK build
+cd /tmp && rm -rf aws-sdk-cpp
+
+# Now build netcdf-c with Zarr support
+git clone --depth 1 --branch zarr-csl-fully https://github.com/mannreis/netcdf-c.git /tmp/netcdf-c
+cd /tmp/netcdf-c
+mkdir build && cd build
+
+cmake .. \
+  -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
+  -DCMAKE_BUILD_TYPE=Release \
+  -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} \
+  -DNETCDF_ENABLE_TESTS=OFF \
+  -DNETCDF_ENABLE_DAP=ON \
+  -DNETCDF_ENABLE_NCZARR=ON \
+  -DNETCDF_ENABLE_S3=ON \
+  -DNETCDF_ENABLE_NCZARR_S3=ON \
+  -DNETCDF_ENABLE_NCZARR_ZIP=ON \
   -DPLUGIN_INSTALL_DIR=${CONDA_PREFIX}/lib/netcdf/plugins
 
-make -j$(nproc)
+make -j2
 make install
 
 # Verify installation
-${CONDA_PREFIX}/bin/ncdump -h 2>&1 | head -5
+which ncdump
+ncdump -h 2>&1 | head -5 || true
 
 # Cleanup
 cd /tmp && rm -rf netcdf-c
 
-# Configure AWS (for anonymous S3 access)
+# Configure AWS for anonymous access
 mkdir -p ${HOME}/.aws
-cat > ${HOME}/.aws/config << EOF
+cat > ${HOME}/.aws/config << 'EOF'
 [default]
 region = eu-central-1
-s3 =
-    signature_version = s3v4
 EOF
 
-cat > ${HOME}/.aws/credentials << EOF
-[default]
-aws_access_key_id = 
-aws_secret_access_key = 
-EOF
+# Set environment variable for anonymous access
+echo "export AWS_NO_SIGN_REQUEST=YES" >> ${HOME}/.bashrc
 
 echo "NetCDF-C with Zarr/S3 support installed successfully"
